### ISSUE TITLE
Crash: Cannot index block IRange(257, 258) with range RoundedOutJRange(JRange(256, 448)) by 255

### ISSUE THREAD

**Issue by jnalanko** [RagnarGrootKoerkamp/astar-pairwise-aligner#29]
Hello, I have a bug report. The following input crashes the CLI tool:

```
>1
TGTACTTCGTTCAGTTACGTATTGCTAAGGTTAAAACCAAGACTCGCTGTGCCTAGTTCAGCACCTAATGATACGGCGACCACCGAGATCTACCTCCCGATACAACACTCTTTCCCTACGACGCTCTTCCGATCTCCGTGATGCAGGGGGTGTTTGTCGAAGTTCACCAGATTTTCATCAAGATGCACGTCATACTCTTTTTTCTCCGGAGGCAGTGCCAGCATGGACTGCTGCTCTTCGAGCCAGCGATCGCAGAAACAGGGACGTGCCTGGATTGTTTCATGCTTTCGTTGGTTAGCGACATCGTGCAGCCAGCGCAGACCGTGGCGGTTGGCTGTTTCAACATCGACAGTGATCCCCATCGGGCGCAGGCGAGTCATTAGTGGGAAG
>2
TTCGTTCAGTTACGTATTGCTAAGGTTAAAACCAAGACTCGCTGTGCCTAGTTCAGCACCTAATGATACGGCGACCACCGAGATCTACACTCGATACAACACTCTTTCCCTACACGACGCTCTTCCGATCTATGTTGGATGATGCAGGGGGTGTTTGTCGAAGTTCACCAGATTTCATCAAGATGCACGTCATACTCTTTTTTCTCCGGAGGCAGTGCCAGCATGGACTGCTGCTCTTCGAGCCAGCGATCGCGGAGACGTGCCTGGATTGTTTCATGCTTTCGTTGGTTAGCGACATCGTGCAGCCAGCGCAGACCGTGGCGGTTGGCTGTTTCAACATCGACAGTGATCCCCATCGGGCGCAGGCGAGTCATTAGTGGGATGTAAAAACTGTTACGGGTGTACTGCACCATCCGTTCCACCCTAGTCA
```

If this file is at test.fna, then the crash happens when I run the following command:

```
RUST_BACKTRACE=full cargo run -r -- -i test.fna
```
```
thread 'main' panicked at astarpa2/src/block.rs:71:9:
Cannot index block IRange(257, 258) with range RoundedOutJRange(JRange(256, 448)) by 255
stack backtrace:
   0:     0x55c99b78c01a - std::backtrace_rs::backtrace::libunwind::trace::h0dd1f5421ecc21b6
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x55c99b78c01a - std::backtrace_rs::backtrace::trace_unsynchronized::h4ce2000f4814e2ec
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c99b78c01a - std::sys::backtrace::_print_fmt::h450cb428d9ffd2eb
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/sys/backtrace.rs:66:9
   3:     0x55c99b78c01a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb932706095e6b6cd
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/sys/backtrace.rs:39:26
   4:     0x55c99b7110b3 - core::fmt::rt::Argument::fmt::h2dee7ff049f45dee
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/fmt/rt.rs:177:76
   5:     0x55c99b7110b3 - core::fmt::write::h251618862a377037
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/fmt/mod.rs:1186:21
   6:     0x55c99b789463 - std::io::Write::write_fmt::he70d9f5fee9bdd3d
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/io/mod.rs:1833:15
   7:     0x55c99b78be72 - std::sys::backtrace::BacktraceLock::print::h98711df25b18f5b8
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/sys/backtrace.rs:42:9
   8:     0x55c99b78cbd9 - std::panicking::default_hook::{{closure}}::h4df2caab414f53fe
   9:     0x55c99b78ca38 - std::panicking::default_hook::h9b3c9177eddb0ab5
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:295:9
  10:     0x55c99b78d184 - std::panicking::rust_panic_with_hook::hab021783e5f06854
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:801:13
  11:     0x55c99b78d02a - std::panicking::begin_panic_handler::{{closure}}::hf1477512f348a63c
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:674:13
  12:     0x55c99b78c4c9 - std::sys::backtrace::__rust_end_short_backtrace::h7df47a37dd45519b
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/sys/backtrace.rs:170:18
  13:     0x55c99b78cccc - rust_begin_unwind
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:665:5
  14:     0x55c99b70f940 - core::panicking::panic_fmt::h7b0c56802b184202
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/panicking.rs:74:14
  15:     0x55c99b6a4211 - astarpa2::block::Block::index::h25be6abac74c8f8e
  16:     0x55c99b66b265 - astarpa2::blocks::trace::<impl astarpa2::blocks::Blocks>::parent::hcbd7b5165634518c
  17:     0x55c99b66e454 - astarpa2::blocks::trace::<impl astarpa2::blocks::Blocks>::trace::h5a6c1287aaad0f6d
  18:     0x55c99b68a5b7 - astarpa2::domain::AstarPa2Instance<V,H>::align_for_bounded_dist::h6d6f5464f76a4273
  19:     0x55c99b68d5f2 - astarpa2::band::exponential_search::h1a9bf3b8539aac71
  20:     0x55c99b6682d9 - astarpa2::AstarPa2<V,H>::cost_or_align::hd156e71bc4629577
  21:     0x55c99b6695bc - <astarpa2::AstarPa2<V,H> as pa_types::Aligner>::align::h44debf6fb2e802e9
  22:     0x55c99b632a42 - pa_bin::main::{{closure}}::h445fc38918c10b18
  23:     0x55c99b631fdc - pa_bin::Cli::process_input_pairs::h156254335b827c40
  24:     0x55c99b62be3d - pa_bin::main::hb09925027e74eef0
  25:     0x55c99b6b2db3 - std::sys::backtrace::__rust_begin_short_backtrace::hd101a07eb32c275e
  26:     0x55c99b629d29 - std::rt::lang_start::{{closure}}::h07f33d65b2105f93
  27:     0x55c99b785398 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfde5ef44103a5d8f
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/core/src/ops/function.rs:284:13
  28:     0x55c99b785398 - std::panicking::try::do_call::h37a79a939801b057
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:557:40
  29:     0x55c99b785398 - std::panicking::try::h426a4488e12e7a62
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:520:19
  30:     0x55c99b785398 - std::panic::catch_unwind::hf1434475f51c9614
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panic.rs:348:14
  31:     0x55c99b785398 - std::rt::lang_start_internal::{{closure}}::hc80838204393a4f5
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/rt.rs:143:48
  32:     0x55c99b785398 - std::panicking::try::do_call::hbfa4ae7b1fb885c2
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:557:40
  33:     0x55c99b785398 - std::panicking::try::hcaf965c14144267b
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panicking.rs:520:19
  34:     0x55c99b785398 - std::panic::catch_unwind::h9adc1ec01dda3b49
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/panic.rs:348:14
  35:     0x55c99b785398 - std::rt::lang_start_internal::h7e4e7408454dc5ed
                               at /rustc/2bd1e894efde3b6be857ad345914a3b1cea51def/library/std/src/rt.rs:143:20
  36:     0x55c99b62bfd5 - main
  37:     0x7fb6927dac87 - __libc_start_main
                               at /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310
  38:     0x55c99b628faa - _start
  39:                0x0 - <unknown>
```

**Comment by RagnarGrootKoerkamp** [comment]
Thanks for the report and small reproducible example!
Have you been using A*PA2 a lot? This feels like a rare edge case to run in to.

What was happening during the traceback:
1. first diagonal transition is tried, the green noise in the bottom right.
2. That's going nowhere, so the full block in blue is recomputed.
3. The distance from the right of the green block, through the blue block, to the end matches the correct distance, so no 'doubling' of the blue block is needed, even though it doesn't fully cover the orange block of the forward pass.
4. The traceback continues, until it reaches the row just above the top of the blue block, at `(258, 255)`. (The blue block starts in row `256`.)
5. Then, no greedy match was possible, and so the cell in the column before was checked at `(257, 255)`.
6. But this cell wasn't computed, so the code panicked.
7. Instead, now I just check whether the cell is out-of-range, and if so, we can always/greedily move left anyway, since we know there was an optimal path through the blue block, and we 'overshot' it too high by greedily extending to the top-left.
8. Indeed we see that the new path goes left for a few steps at the top of the blue block, and then resumes.

As you see, this feels like a rare edge case. But maybe it's not actually that rare and just nobody has used it much :sweat_smile: 

![image](https://github.com/user-attachments/assets/efeac1c2-0f20-48d0-b009-317fe64ed52d)

**Comment by jnalanko** [comment]
Thanks for the quick fix! This was my first time running A*PA2, but it was a big run involving a few gigabytes of sequences, so I guess it worked as a stress test.

**Comment by RagnarGrootKoerkamp** [comment]
Cool! Let me know if you run into more issue then :)
