### ISSUE TITLE
Crash: No trace found through block IRange(0, 256) RoundedOutJRange(JRange(0, 320))

### ISSUE THREAD

**Issue by jnalanko** [RagnarGrootKoerkamp/astar-pairwise-aligner#30]
Hello, thanks for writing A*PA2! It's very useful for me. 

I have another bug report. I have a crash with the following input:

```
>1
CTTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTCAAGCAGAAGACGGCATACGAGATAGCTTGGCGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTCTGTAGTTCACTGATTTTGAGCTAACCGACAGCAGAGACGCTGAACGGCTGGACCGATTTGCGCAAACGGCAGACGAGATACGTATTGCTGACCGGGGATTCGGTTCGCGTCCCGAATGTATCCGCTCACTTGCTTTTGGAGAAGCTGATTATATCGTCCGGGTTCACTGGCGAGGATTGCGCTGGTTAACTGCAGAAGGAATGCGCTTTGACATGATGGGTTTTCTGCGCGGGCTGGATTGCGGTAAGAACGGTGAAACCACTGTAATGATAGGCAATTCAGGTAATAAAAAAGCCGGAGCTCCCTTTCCGGCACGTCATTGTGTATCACTTCCTCGAAAAAGCATTAATCACGA
>2
TGTACTTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTCAAGCAGAAGACGGCATACGAAATAGCTTGGCGTGACTGGAGTTCAGACGTATCTTCGATCTTCCTTGAGACGTGCCGGAAAGGGAGCTCCGGCTTTTTATTACCTGAATTGCCTATCATTACAGTGGTTTCACCGTTCTTACCGCAATCCAGCCCGCGCAGAAAACCCATCATGTCAAAGCGCATTCCTTCTGCAGTTAACCAGCGCAATCCTCGCCAGTGAACCCGGACGATATAATCAGCTTCTCCAAAAGCAAGTGAGCGGATACATTCGGGACGCGAACCGAATCCCCGGTCAGCAATACGTATCTCGTCTGCCGTTTGCGCAAATCGGTCCAGCCGTTCAGCGTCTCTGCTATCGGTTAGCTCAAAATCAGTGAACTGACGGGTATGAGGATCATATCCCATATGTAGTCGCCAGAA
```

To replicate, put this in test.fna, and run `RUST_BACKTRACE=1 cargo run -- -i test.fna`. This causes a panic with the following backtrace:

```
thread 'main' panicked at astarpa2/src/blocks/trace.rs:113:25:
No trace found through block IRange(0, 256) RoundedOutJRange(JRange(0, 320))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/panicking.rs:74:14
   2: astarpa2::blocks::trace::<impl astarpa2::blocks::Blocks>::trace
             at ./astarpa2/src/blocks/trace.rs:113:25
   3: astarpa2::domain::AstarPa2Instance<V,H>::align_for_bounded_dist
             at ./astarpa2/src/domain.rs:526:40
   4: astarpa2::AstarPa2<V,H>::cost_or_align::{{closure}}
             at ./astarpa2/src/lib.rs:147:21
   5: astarpa2::band::exponential_search
             at ./astarpa2/src/band.rs:116:34
   6: astarpa2::AstarPa2<V,H>::cost_or_align
             at ./astarpa2/src/lib.rs:146:25
   7: <astarpa2::AstarPa2<V,H> as pa_types::Aligner>::align
             at ./astarpa2/src/lib.rs:206:37
   8: pa_bin::main::{{closure}}
             at ./pa-bin/src/main.rs:28:29
   9: pa_bin::Cli::process_input_pairs
             at ./pa-bin/src/lib.rs:105:33
  10: pa_bin::main
             at ./pa-bin/src/main.rs:26:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/ed04567ba1d5956d1080fb8121caa005ce059e12/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by RagnarGrootKoerkamp** [comment]
Ah yes; my previous bugfix was just completely broken and compared with the wrong side of the interval. Somewhat surprisingly that did fix that particular case, but I forgot to run tests and basically all were broken :sweat_smile:
